name: Deploy to Production

on:
 push: 
  branches: 
  - main
  
jobs:
 deploy: 
   runs-on: ubuntu-latest 
 # Setting environment variables at the job level
   env: 
    DEPLOY_ENV: production 
    S3_BUCKET: my-production-bucket 
   steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3 
      with: 
       node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build the project 
      run: npm run build 
    - name: Deploy to S3 
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      run: | 
       echo "Deploying to $S3_BUCKET in $DEPLOY_ENV environment"
       npm install -g aws-cli
       aws s3 sync ./build s3://$S3_BUCKET --delete
