name: Deploy to Production

on:
 push: 
  branches: 
  - main
  
jobs:
 deploy: 
   runs-on: ubuntu-latest 
 # Setting environment variables at the job level
   env: 
    DEPLOY_ENV: production 
    SITE_TITLE: "MY STATIC SITE" 
   steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3 
      with: 
       node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build the project 
      run: |
       echo "Building for $DEPLOY_ENV environment"
       echo "Site title is $SITE_TITLE"
       npm run build
    - name: Deploy to github pages 
      uses: peaceiris/actions-gh-pages@v3
      with:
       github_token: ${{ secrets.GITHUB_TOKEN}}
       publish_dir: ./build
        
